# """
# Django settings for server project.
#
# Generated by 'django-admin startproject' using Django 1.8.13.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/1.8/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.8/ref/settings/
# """
#
# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# import os
#
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'v80m@@@0hm%gmr+wvm5whi7t4l2ib1#n=)%*kwg(m)!bwol=9o'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = [
#     '127.0.0.1',
#     '*',
#     '13.125.82.234'
# ]
#
# # Application definition
#
# INSTALLED_APPS = (
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'corsheaders',
#     'lib',
#     'angel_instrument'
# )
# #
# # WEBPACK_LOADER = {
# #     {
# #         'DIRS' : [os.path.join(BASE_DIR, 'webpeck-stats.dev.json')]
# #     }
# # }
#
#
# #
# # STATICFILES_DIRS = [
# #     os.path.join('assets')
# # ]
#
# MIDDLEWARE_CLASSES = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# CORS_ORIGIN_ALLOW_ALL = True
#
# CORS_ORIGIN_WHITELIST = [
#     'http://127.0.0.1:3000',
#     'http://127.0.0.1:8000'
# ]
#
# # CORS_ALLOW_METHODS = (
# #     'DELETE',
# #     'GET',
# #     'OPTIONS',
# #     'PATCH',
# #     'POST',
# #     'PUT',
# # )
# #
# # CORS_ALLOW_HEADERS = (
# #     'accept',
# #     'accept-encoding',
# #     'authorization',
# #     'content-type',
# #     'dnt',
# #     'origin',
# #     'user-agent',
# #     'x-csrftoken',
# #     'x-requested-with',
# # )
#
#
# SILENCED_SYSTEM_CHECKS = [
#     'admin.E408',
#     'admin.E409',
#     'admin.E410'
# ]
#
# ROOT_URLCONF = 'server.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'server.wsgi.application'
#
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10
# }
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'music',
#         'USER': 'wooseok',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
#
# # Internationalization
# # https://docs.djangoproject.com/en/1.8/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.8/howto/static-files/
#
# STATIC_URL = '/static/'
